### ISSUE TITLE
lodash overriding

### ISSUE THREAD

**Issue by Et3rnal** [maximelafarie/ngx-smart-loader#16]
**This is more of a question than an issue!**

I noticed after upgrading to v2.0 I have a page which uses underscore js (externally loaded) started using Lodash that coming from node_modules!

My angular app which uses smart loader is loaded into the same page, I found out about this because of `.pluck` not in Lodash and after debugging I found that preop to the upgrade this page would use underscore js which is at the header of the page and not and after the upgrade it started to use Lodash!

I wonder if you have changed how you load your dependencies? or anything else that might help me understand how did that happen!

_PS: I know that page if a big mess but its a legacy app and we are migrating slowly._

Thanks for the great library.

**Comment by maximelafarie** [comment]
Hi @Et3rnal,
As you can see in the `package.json` file under `ngx-smart-loader` folder, it doesn't need anything else that the defined `peerDependencies`:

```json
...
"peerDependencies": {
    "@angular/common": ">= 5.0.0",
    "@angular/core": ">= 5.0.0"
},
...
```
So don't worry about any breaking changes with the dependencies! 😉
Thank you very much for the kind words!
Cheers! 🖖
